### ISSUE TITLE
Ошибка с FAWE

### ISSUE THREAD

**Issue by Sqw6qq** [EpicPlayerA10/IA-Edit#1]
FAWE работал, но, в один момент начал не работать. В plugins он подсвечивается зелёным, но, не работает. На сервере также есть PlotSquared (у меня режим Креатив) и WorldGuard. Я пытался скачать самые новые версии, но везде пишет одно и тоже. Скачал буквально все версии, и никакая из них не стала работать. Вот логи, может там есть ответ на мою ошибку https://pastes.dev/bZiUaXtyg9

**Comment by EpicPlayerA10** [comment]
That issue has nothing to do with `IA-Edit` plugin. Please create an issue here https://github.com/IntellectualSites/FastAsyncWorldEdit
(You are probably running wrong version of FAWE that is not for 1.16.5)
